# Generated by Django 2.0.4 on 2018-05-09 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.AddField(
            model_name='item',
            name='added_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='item',
            name='expires_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='item',
            name='where',
            field=models.IntegerField(choices=[(1, 'Kitchen: Top tray'), (2, 'Kitchen: Middle drawer'), (3, 'Kitchen: Bottom drawer'), (4, 'Utility: Top tray'), (5, 'Utility: 1st drawer'), (6, 'Utility: 2nd drawer'), (7, 'Utility: 3rd drawer'), (8, 'Utility: 4th drawer'), (9, 'Utility: 5th drawer')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Raw meat'), (2, 'Fruit and veg'), (3, 'Meal'), (4, 'Dessert'), (5, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='food'),
        ),
    ]
